### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 ().

### ISSUE THREAD

**Issue by haddadnidal** [samuelcesc/risevision-nodejs#1]
Hi, first of all great work and thank you.

I've downloaded your code and i am running  it on my VPS and keep gettting this error in the console `https://content.googleapis.com/discovery/v1/apis/core/v1/rest?fields=kind%2Cname%2Cversion%2CrootUrl%2CservicePath%2Cresources%2Cparameters%2Cmethods&pp=0`

`Failed to load resource: the server responded with a status of 404 ().`

and `core.company.get.js:22 Uncaught TypeError: Cannot read property 'company' of undefined`.
Am i doing this wrong and if yes tell me how to fix.

Thank you.

**Comment by samuelcesc** [comment]
Hello @neeeeds , do you have your Google endpoints setup already using the Google API console?

If yes, setup your client_id in public/javascripts folder.

Also, let me know what port you are running on.

**Comment by haddadnidal** [comment]
hi @samuelcesc yes i did setup the google endpoints if by that you mean creating a new project in google dev  console and changing the client_id in the auth.js file. 
Is there any additionnal steps to do ?

**Comment by samuelcesc** [comment]
That is supposed to work.

What port are you using? 80 or 3000?

**Comment by haddadnidal** [comment]
Port 3000
I Can access all the assests ans the static html pages but when i execute  a simple company get i get this error 

![capture d ecran 2016-08-25 a 17 25 18](https://cloud.githubusercontent.com/assets/9222035/17975177/01827e80-6ae9-11e6-896f-bcafd3772515.png)
![capture d ecran 2016-08-25 a 17 25 20](https://cloud.githubusercontent.com/assets/9222035/17975181/0495269a-6ae9-11e6-864b-74bac2aae9b4.png)

This is screenshot of the webpage both localhost ans VPS server.

**Comment by haddadnidal** [comment]
hi there, i figured out the problem whei i set the ROOT to production manually i workes, the problem was using the ROOT in stage mode. So this issue is closed.
`var ROOT = 'https://rvaserver2.appspot.com/_ah/api';
`
this is how i did a workaround to get it to work in localhost
Thank you
